/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119445-g0f751d3836-20250507"
#endif /* AVUTIL_FFVERSION_H */
