/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118517-g2066c5526d-20250221"
#endif /* AVUTIL_FFVERSION_H */
